config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :jobs do
    resources :resumes
  end

  namespace :admin do
    resources :jobs do
      member do
        post :hide
        post :public
      end
      resources :resumes
    end
  end

  resources :resumes

  root 'jobs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true

  belongs_to :user
  has_many :resumes

  def hide!
    self.is_hidden = true
    self.save
  end

  def public!
    self.is_hidden = false
    self.save
  end

end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job

  mount_uploader :attachment, AttachmentUploader

  validates :attachment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end

  has_many :jobs
  has_many :resumes

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :admin_required
  layout "admin"

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def show
    @job = Job.find(params[:id])
    @resumes = @job.resumes
  end

  def edit
    @job = Job.find(params[:id])

    if current_user != @job.user
      redirect_to root_path
    end
  end

  def update
    @job = Job.find(params[:id])

    if current_user != @job.user
      redirect_to root_path
    end

    if @job.update(job_params)
      redirect_to admin_job_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    if current_user != @job.user
      redirect_to root_path
    else
      @job.destroy
      redirect_to admin_jobs_path
    end
  end

  def hide
    @job = Job.find(params[:id])

    @job.hide!

    redirect_to request.referer
  end

  def public
    @job = Job.find(params[:id])

    @job.public!

    redirect_to request.referer
  end


  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden)
  end
end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_required
    if !current_user.admin?
      redirect_to "/"
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  def index
    @jobs = case params[:order]
            when 'by_lower_bound'
            Job.where(:is_hidden => false).order('wage_lower_bound DESC')
            when 'by_upper_bound'
            Job.where(:is_hidden => false).order('wage_upper_bound DESC')
            else
            Job.where(:is_hidden => false).order("created_at DESC")
            end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user

    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])

    if current_user != @job.user
      redirect_to root_path
    end
  end

  def update
    @job = Job.find(params[:id])

    if current_user != @job.user
      redirect_to root_path
    end

    if @job.update(job_params)
      redirect_to job_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    if current_user != @job.user
      redirect_to root_path
    else
      @job.destroy
      redirect_to jobs_path
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :description)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def create
    @job = Job.find(params[:job_id])
    @resume = @job.resumes.new(resume_params)
    @resume.user = current_user

    if @resume.save
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  private

  def resume_params
    params.require(:resume).permit(:body, :attachment)
  end

end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-low-vision")
    else
      content_tag(:span, "", :class => "fa fa-globe" )
    end
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/admin/jobs/edit.html.erb
<h1>Edit job</h1>

<%= simple_form_for [:admin, @job] do |f| %>
<div class="group">
  <%= f.input :title %>
</div>
<div class="group">
  <%= f.input :description %>
</div>
<div class="group">
  <%= f.input :wage_lower_bound %>
</div>
<div class="group">
  <%= f.input :wage_upper_bound %>
</div>
<div class="group">
  <%= f.input :contact_email %>
</div>
<div class="group">
  <%= f.input :is_hidden %>
</div>
<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to("New job", new_admin_job_path, :class => "btn btn-default" ) %>
</div>

<br><br>

<table class="table table-boldered">
  <thead>
    <tr>
      <td>职缺(投递数量)</td>
      <td>薪资下限</td>
      <td>薪资上限</td>
      <td>管理选项</td>
      <td>刊登时间</td>
    </tr>
  </thead>
  <% @jobs.each do |job| %>
  <tr>
    <td>
      <%= render_job_status(job) %>

      <%= link_to job.title, admin_job_path(job) %> (<%= job.resumes.count %>)
    </td>
    <td>
      <%= job.wage_lower_bound %>
    </td>
    <td>
      <%= job.wage_upper_bound %>
    </td>
    <td>
      <%= link_to("Edit", edit_admin_job_path(job)) %>
      |
      <%= link_to("Delete", admin_job_path(job), :method => :delete, :data => { :confirm => "Are you sure?" }) %>
      |
      <% if job.is_hidden %>
      <%= link_to "Public", public_admin_job_path(job), :method => :post, class: "btn btn-sm btn-default" %>
      <% else %>
      <%= link_to "Hide", hide_admin_job_path(job), :method => :post, class: "btn btn-sm btn-default" %>
      <% end %>

    </td>
    <td>
      <%= job.created_at %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin/jobs/new.html.erb
<h1>Add a job</h1>

<%= simple_form_for [:admin, @job] do |f| %>
<div class="group">
  <%= f.input :title %>
</div>
<div class="group">
  <%= f.input :description %>
</div>
<div class="group">
  <%= f.input :wage_lower_bound %>
</div>
<div class="group">
  <%= f.input :wage_upper_bound %>
</div>
<div class="group">
  <%= f.input :contact_email %>
</div>
<div class="group">
  <%= f.input :is_hidden %>
</div>
<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/admin/jobs/show.html.erb
<h1><%= @job.title %></h1>
<%= simple_form_for @job do |f| %>
<div class="group">
  <h3><%= simple_format(@job.description) %></h3>
</div>
<div class="pull-right">
  <%= link_to 'Back', jobs_path, class: "btn btn-default" %>
</div>
<div class="group">
  <h4><%= f.label :薪资范围 %>:
    <br>
    <%= @job.wage_lower_bound %>
    -
    <%=  @job.wage_upper_bound %>
    <h4></div>
    <div class="group">
      <h4><%= f.label :联系邮件 %>：
        <br>
        <%= @job.contact_email %>
        <h4></div>
        <% end %>
        <hr>

        <div class="resumes">
          <%= render "admin/resumes/resumes" %>
        </div>

app/views/admin/resumes/_resumes.html.erb
<h2 class="text-center">简历明细——有
  <%= @job.resumes.count %>
  封简历</h2>
<% @resumes.each do |resume| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-12">
        <h3 class="panel-title">
          <p>
            <small>Submitted
              <strong><%= time_ago_in_words(resume.created_at) %>
                ago</strong>
              by
              <%= resume.user.email %></small>
          </p>
        </h3>
      </div>

    </div>
  </div>
  <div class="panel-body">
    <div class="trix-content">
      <p>
        <%= simple_format(resume.body) %>
      </p>
    </div>
    <hr>

    <% if resume.attachment.present? %>
    <i class="fa fa-paperclip"></i>
    <%= link_to("Download Resume", resume.attachment_url) %>
  <% else %>
    No Attachment
    <% end %>
  </div>
</div>
<% end %>

app/views/common/_flashes.html.erb
<% flash.each do |name, msg| %>
<%= content_tag(:div, msg, class: "alert") %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">=©2017 joblisting2.0
    <br>by 难念的经
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Job Listing</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
        <li><%= link_to "注册", new_user_registration_path %></li>
        <li><%= link_to "登入", new_user_session_path %></li>
      <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Hi!,
            <%= current_user.email %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% if current_user.admin? %>
            <li>
              <%= link_to "Admin 选单", admin_jobs_path %>
            </li>
            <% end %>
            <li>
              <%= link_to "登出", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/jobs/edit.html.erb
<h1>Edit job</h1>

<%= simple_form_for @job do |f| %>
<div class="group">
  <%= f.input :title %>
</div>
<div class="group">
  <%= f.input :description %>
</div>
<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/jobs/index.html.erb
<div class="dropdown clearfix pull-right">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        排序
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
        <li>
            <%= link_to("按薪资下限排序", jobs_path(:order => "by_lower_bound")) %>
        </li>
        <li>
            <%= link_to("按薪资上限排序", jobs_path(:order => "by_upper_bound")) %>
        </li>
        <li>
            <%= link_to("按薪发表时间排序", jobs_path ) %>
        </li>
    </ul>
</div>

<table class="table table-boldered">
    <thead>
        <tr>
            <th>职缺</th>
            <th>薪资上限</th>
            <th>薪资下限</th>
            <th>刊登时间</th>
        </tr>
    </thead>

    <tbody>
        <% @jobs.each do |job| %>

        <tr>
            <td><%= link_to(job.title, job_path(job)) %></td>
            <td><%= job.wage_upper_bound %></td>
            <td><%= job.wage_lower_bound %></td>
            <td><%= job.created_at %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/jobs/new.html.erb
<h1>Add a job</h1>

<%= simple_form_for @job do |f| %>
<div class="group">
  <%= f.input :title %>
</div>
<div class="group">
  <%= f.input :description %>
</div>
<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<%= simple_form_for @job do |f| %>
<div class="group">
  <h3><%= simple_format(@job.description) %></h3>
</div>
<div class="pull-right">
  <%= link_to 'Back', jobs_path, class: "btn btn-default" %>
</div>
<div class="group">
  <h4><%= f.label :薪资范围 %>:
    <br>
    <%= @job.wage_lower_bound %>
    -
    <%=  @job.wage_upper_bound %>
    <h4></div>
    <div class="group">
      <h4><%= f.label :联系邮件 %>：
        <br>
        <%= @job.contact_email %>
        <h4></div>
        <% end %>
        <hr>

        <h2>投递简历</h2>
        <%= simple_form_for [@job, Resume.new] do |f| %>
        <div class="group">
          <%= f.input :body, class: "form_control "%>
        </div>
        <div class="well">
          <%= f.label :attachment %>
          <%= f.file_field :attachment %>
        </div>
        <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Job Listing</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag     'application', media: 'all', 'data_turbolinks-track': 'reload' %>
        <%= javascript_include_tag  'application', 'data_turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <div class="row">
                <div class="col-md-2">
                    <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
                        <li class="active">
                            <%= link_to("Jobs", admin_jobs_path ) %>
                        </li>

                    </ul>
                </div>

                <div class="col-md-10">
                    <%= yield %>
                </div>
            </div>
        </div>

        <%= render "common/footer" %>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Joblisting20</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    
    <%= render "common/footer" %>
  </body>
</html>